/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as RutinaSlugRouteImport } from './routes/rutina.$slug'
import { Route as SetSlugRouteImport } from './routes/set.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaSlugRoute = RutinaSlugRouteImport.update({
  id: '/rutina/$slug',
  path: '/rutina/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SetSlugRoute = SetSlugRouteImport.update({
  id: '/set/$slug',
  path: '/set/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$slug': typeof PSlugRoute
  '/rutina/$slug': typeof RutinaSlugRoute
  '/set/$slug': typeof SetSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$slug': typeof PSlugRoute
  '/rutina/$slug': typeof RutinaSlugRoute
  '/set/$slug': typeof SetSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$slug': typeof PSlugRoute
  '/rutina/$slug': typeof RutinaSlugRoute
  '/set/$slug': typeof SetSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$slug' | '/rutina/$slug' | '/set/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$slug' | '/rutina/$slug' | '/set/$slug'
  id: '__root__' | '/' | '/p/$slug' | '/rutina/$slug' | '/set/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PSlugRoute: typeof PSlugRoute
  RutinaSlugRoute: typeof RutinaSlugRoute
  SetSlugRoute: typeof SetSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina/$slug': {
      id: '/rutina/$slug'
      path: '/rutina/$slug'
      fullPath: '/rutina/$slug'
      preLoaderRoute: typeof RutinaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set/$slug': {
      id: '/set/$slug'
      path: '/set/$slug'
      fullPath: '/set/$slug'
      preLoaderRoute: typeof SetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PSlugRoute: PSlugRoute,
  RutinaSlugRoute: RutinaSlugRoute,
  SetSlugRoute: SetSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
